name: 'OCaml Test Action'
description: 'Test OCaml and getting output string'
inputs:
  issue_num:  # issue number
    description: 'Number of the issue'
    required: true
  issue_contents: # issue contents
    description: 'Contents of the issue'
    required: true
  repository_path_name: # repository name
    description: 'Path name of the repository'
    required: true
  rapid_key: # RapidAPI's key
    description: 'Key for the RapidAPI'
    required: true
  repo_key: # GitHub access token
    description: 'Acees token for GitHub'
    required: true 
outputs:
  string: # output of string
    description: 'The contents of issue'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.issue_num }}
    - ${{ inputs.issue_contents }}
    - ${{ inputs.repository_path_name }}
    - ${{ inputs.rapid_key }}
    - ${{ inputs.repo_key }}